# NumPy

In [55]:
import numpy as np

## Create an Array
Write a Python program that creates an integer array with 4 elements of type unsigned int16 and prints the shape, the number of dimensions, and the length of each element in bytes.

In [56]:
array_1 = np.array([1, 2, 3, 4], dtype=np.uint16)
print(array_1)
print(array_1.shape)
print(array_1.ndim)
print(array_1.itemsize)

[1 2 3 4]
(4,)
1
2


## Create a 2D Array
Write a Python program that creates a $ 5 \times 2 $ integer array from a range between 100 to 200 such that the difference between each element is 10.

In [57]:
array_2 = np.arange(100, 200, 10).reshape(5, 2)
array_2

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

## Select Rows and Columns
Write a Python program to return the 2D array of odd rows and even columns from the given numpy array.

In [58]:
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
a

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [59]:
odd_rows = a[1::2]
print(odd_rows)
print("_______________________________")
even_columns = a[:, 0::2]
print(even_columns)

[[15 18 21 24]
 [39 42 45 48]]
_______________________________
[[ 3  9]
 [15 21]
 [27 33]
 [39 45]
 [51 57]]


## Compute Numerical Operations
Write a Python program that computes the sum, the element-wise multiplication, and the matrix multiplication of the given numpy arrays.

In [60]:
a = np.array([[5, 6], [21, 18]])
b = np.array([[15, 33], [4, 7]])
a, b

(array([[ 5,  6],
        [21, 18]]),
 array([[15, 33],
        [ 4,  7]]))

In [61]:
sum = a + b
print(sum)
print("_______________________________")
multiplication = a * b
print(multiplication)
print("_______________________________")
matrix_multiplication = a.dot(b)
print(matrix_multiplication)

[[20 39]
 [25 25]]
_______________________________
[[ 75 198]
 [ 84 126]]
_______________________________
[[ 99 207]
 [387 819]]


## Split and Concatenate an Array
Write a Python program to split the given $ 8 \times 3 $ array into 4 equal-sized $ 2 \times 3 $ sub-arrays. Then, concatenate the splitted arrays vertically to rebuilt the original array.

In [62]:
a = np.arange(10, 34, 1).reshape(8, 3)
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [63]:
from IPython.display import display

split_array = np.array_split(a, 4)
display(split_array)
print("____________________________")
conc = np.concatenate(split_array)
conc

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

____________________________


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

## Replace a Column
Write a Python program that replaces the second column from the given array with the new given column.

In [64]:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
new_column = np.array([[10, 10, 10]])
a, new_column

(array([[34, 43, 73],
        [82, 22, 12],
        [53, 94, 66]]),
 array([[10, 10, 10]]))

In [65]:
a[1] = new_column
a

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

## Sort Rows and Columns
Write a Python program to sort the given 2D array in 2 scenarios: (1) Sort the rows; (2) Sort the columns.  

In [66]:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
a

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [67]:
sort_column = np.sort(a, axis=0)
print(sort_column)
print("_______________________________")
sort_row = np.sort(a, axis=1)
print(sort_row)

[[34 22 12]
 [53 43 66]
 [82 94 73]]
_______________________________
[[34 43 73]
 [12 22 82]
 [53 66 94]]
